# Generated by Django 4.1.2 on 2022-10-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('front', models.FileField(upload_to='Cards/front/')),
                ('back', models.FileField(upload_to='Cards/back/')),
            ],
        ),
    ]
