# Generated by Django 4.1.2 on 2022-10-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingg', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='side',
            field=models.ImageField(blank=True, null=True, upload_to='Cards/side/'),
        ),
    ]
