# Generated by Django 4.1.2 on 2023-01-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingg', '0003_card_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='side',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
